// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatformService.Repository;

#nullable disable

namespace PlatformService.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231217103749_init_01")]
    partial class init_01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlatformService.Models.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kubanetes",
                            Publisher = "Google",
                            Version = "1.0.0"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Docker",
                            Publisher = "Google",
                            Version = "1.0.0"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Asure",
                            Publisher = "Microsoft",
                            Version = "1.0.0"
                        },
                        new
                        {
                            Id = 4,
                            Name = "AWS",
                            Publisher = "Amason",
                            Version = "1.0.0"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
