apiVersion: batch/v1
kind: Job
metadata:
  name: ef-database-update-job
spec:
  template:
    spec:
      containers:
      - name: platformservice
        image: sankadharmapala/platformservice:latest
        command: [ "dotnet", "ef", "database", "update" ]
      restartPolicy: Never
